// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbTYwk5ZbhFxQdBkxuI64nSYMXg6DdXQ',
    appId: '1:376064786660:web:2f19d4daa91e5c6b85ecf1',
    messagingSenderId: '376064786660',
    projectId: 'cricklyzer-app',
    authDomain: 'cricklyzer-app.firebaseapp.com',
    storageBucket: 'cricklyzer-app.appspot.com',
    measurementId: 'G-JZCZFBVJPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfZZa2WR3mmlHjOUWKGaefiLmj5iDgoQ',
    appId: '1:376064786660:android:fd6090d924b6e0fd85ecf1',
    messagingSenderId: '376064786660',
    projectId: 'cricklyzer-app',
    storageBucket: 'cricklyzer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hNPe-xeJs1n6T95e0NIU9tVwduAHs24',
    appId: '1:376064786660:ios:2b8aa8da950d68a785ecf1',
    messagingSenderId: '376064786660',
    projectId: 'cricklyzer-app',
    storageBucket: 'cricklyzer-app.appspot.com',
    androidClientId: '376064786660-8j6k3li9flbjcjcfga8od4eg55hifk3c.apps.googleusercontent.com',
    iosClientId: '376064786660-rdbcr4nlm99hq6d26p5i983jjfhh91kt.apps.googleusercontent.com',
    iosBundleId: 'com.nosh.cricklyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hNPe-xeJs1n6T95e0NIU9tVwduAHs24',
    appId: '1:376064786660:ios:2b8aa8da950d68a785ecf1',
    messagingSenderId: '376064786660',
    projectId: 'cricklyzer-app',
    storageBucket: 'cricklyzer-app.appspot.com',
    androidClientId: '376064786660-8j6k3li9flbjcjcfga8od4eg55hifk3c.apps.googleusercontent.com',
    iosClientId: '376064786660-rdbcr4nlm99hq6d26p5i983jjfhh91kt.apps.googleusercontent.com',
    iosBundleId: 'com.nosh.cricklyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbTYwk5ZbhFxQdBkxuI64nSYMXg6DdXQ',
    appId: '1:376064786660:web:1b12fcf67d9125e185ecf1',
    messagingSenderId: '376064786660',
    projectId: 'cricklyzer-app',
    authDomain: 'cricklyzer-app.firebaseapp.com',
    storageBucket: 'cricklyzer-app.appspot.com',
    measurementId: 'G-PNFPBRSK50',
  );
}
